// Published challenges in a workspace: listing, locking, unlocking, index.
import { existsSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { challengeStatus, readEvents } from "./progress.mjs";
import { readManifest } from "./runner.mjs";
import { LOCK_FILE, collectFiles, encryptBundle, parseHints, readBundle, writeFiles } from "./vault.mjs";
import { UserError } from "./workspace.mjs";

export const LOCKED_PARTS = ["solution", "bugs", "hints.md"];

export function challengesDir(ws) {
  return join(ws, "challenges");
}

export function listChallenges(ws) {
  const root = challengesDir(ws);
  if (!existsSync(root)) return [];
  return readdirSync(root)
    .filter((name) => existsSync(join(root, name, "challenge.json")))
    .sort()
    .map((name) => ({ dir: join(root, name), manifest: readManifest(join(root, name)) }));
}

/** By id/prefix, or the newest still-open challenge, or the newest one. */
export function pickChallenge(ws, idOrPrefix) {
  const all = listChallenges(ws);
  if (all.length === 0) throw new UserError("No challenges yet. Run `ginga new <lang>` or `ginga daily`.");
  if (idOrPrefix) {
    const hits = all.filter((c) => c.manifest.id === idOrPrefix || c.manifest.id.startsWith(idOrPrefix) || c.dir.endsWith(idOrPrefix));
    if (hits.length === 1) return hits[0];
    if (hits.length === 0) throw new UserError(`No challenge matches "${idOrPrefix}".`);
    throw new UserError(`"${idOrPrefix}" is ambiguous: ${hits.map((h) => h.manifest.id).join(", ")}`);
  }
  const events = readEvents(ws);
  const open = all.filter((c) => challengeStatus(events, c.manifest.id).status === "open");
  return (open.length ? open : all).at(-1);
}

export function isLocked(dir) {
  return existsSync(join(dir, LOCK_FILE));
}

/** Encrypt solution/, bugs/ and hints.md with the README key, then delete the plaintext. */
export function lockChallenge(dir) {
  const files = collectFiles(dir, LOCKED_PARTS);
  writeFileSync(join(dir, LOCK_FILE), encryptBundle(files, readFileSync(join(dir, "README.md"))));
  for (const part of LOCKED_PARTS) rmSync(join(dir, part), { recursive: true, force: true });
}

/** Decrypt into the challenge dir and remove the lock file. */
export function unlockChallenge(dir) {
  if (!isLocked(dir)) return false;
  writeFiles(dir, readBundle(dir));
  rmSync(join(dir, LOCK_FILE));
  return true;
}

/** Hints for a challenge, whether locked or already unlocked. */
export function readHints(dir) {
  if (isLocked(dir)) {
    const bundle = readBundle(dir);
    return parseHints(bundle["hints.md"]?.toString("utf8") ?? "");
  }
  const p = join(dir, "hints.md");
  return existsSync(p) ? parseHints(readFileSync(p, "utf8")) : [];
}

export function writeIndex(ws) {
  const events = readEvents(ws);
  const icon = { open: "⬜", solved: "✅", gaveup: "🟥" };
  const rows = listChallenges(ws)
    .reverse()
    .map(({ manifest: m }) => {
      const s = challengeStatus(events, m.id);
      return `| ${m.date} | ${m.lang} | L${m.level} | [${m.title}](challenges/${m.id}/README.md) | ${m.type} | ${icon[s.status]} ${s.status} |`;
    });
  writeFileSync(
    join(ws, "INDEX.md"),
    [
      "# Challenges",
      "",
      "Generated by `ginga`; do not edit by hand.",
      "",
      "| Date | Lang | Level | Challenge | Type | Status |",
      "|---|---|---|---|---|---|",
      ...rows,
      "",
    ].join("\n"),
  );
}
