/* Golden cases: inputs from a fixed seed, expected counts from the reference. */
static const struct { const char *text; size_t words; } CASES[] = {
    {"", 0},
    {"x1", 1},
    {"a --\rcaf\xc3""\xa9""", 3},
    {"\v! --\t!  caf\xc3""\xa9""\tword\nx1", 6},
    {"\f-- x1", 2},
    {"\fx1\v--  x1\ncaf\xc3""\xa9""\tword\vx1\r", 6},
    {"x1\tword ", 2},
    {" !\fword\ra\na", 4},
    {"--  a\fcaf\xc3""\xa9""  a\fcaf\xc3""\xa9""  caf\xc3""\xa9""\v", 6},
    {"!", 1},
    {"\n", 0},
    {"caf\xc3""\xa9""", 1},
    {"a\na\r!", 3},
    {"-- ", 1},
    {"caf\xc3""\xa9""\ta\fword\f--\n--\nword\t", 6},
    {"word", 1},
    {"caf\xc3""\xa9"" x1\ta\vx1 word  ", 5},
    {" --", 1},
    {"word  a --\vcaf\xc3""\xa9""\rword", 5},
    {"word\f!\n--  a\va\r", 5},
    {"caf\xc3""\xa9""\f--", 2},
    {"  --  caf\xc3""\xa9""\nx1 --\f!\r", 5},
    {"caf\xc3""\xa9""\tcaf\xc3""\xa9""\v!\n", 3},
    {"a a\r!", 3},
    {" --  word\vword a\t!", 5},
    {"x1  --\t-- word", 4},
    {"", 0},
    {"  --\n!", 2},
    {"word\ncaf\xc3""\xa9"" !\tcaf\xc3""\xa9""\n--\t", 5},
    {"", 0},
    {"x1  word\n--\tword  ", 4},
    {"\t", 0},
};
